language: php
php:
  - '5.6'
  - '7.0'
services:
  - mysql
before_script:
  - composer install
  - mv tests/test_env .env
  - mysql -e 'CREATE DATABASE polrci;'
  - php artisan migrate --force
  - composer install
notifications:
  email: false
